#!/usr/bin/env bash
# install and configure HAproxy on lb-01 server

# colors
blue='\e[1;34m'
green='\e[1;32m'
reset='\033[0m'

echo -e "\n${blue}Updating and upgrading packages...${reset}\n"
sudo apt-get -qq update && sudo apt-get -qq upgrade

echo -e "\n${blue}Installing HAproxy on Ubuntu 16.04...${reset}\n"
sudo apt-get -qq install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get -qq install haproxy

echo -e "\n${blue}Configuring HAproxy...${reset}\n"
DomainName='notedowntocode.tech'
InitFile='/etc/default/haproxy'
ConfigFile='/etc/haproxy/haproxy.cfg'
HAproxy_config="\
#--${DomainName}--
backend ${DomainName}-backend
    balance roundrobin
    server web-01 107.21.40.97:80 check
    server web-02 54.87.240.211:80 check

frontend ${DomainName}-frontend
    bind *:80
    default_backend ${DomainName}-backend
#--${DomainName}--
"
[ -f $InitFile ] || touch $InitFile
[ -f $ConfigFile ] || touch $ConfigFile

ConfigWords=$(grep -Eco "${DomainName}-backend" $ConfigFile)

if [ "$(grep -Eco '^ENABLED=[01]$' $InitFile)" -gt 0 ]; then
        sudo sed -i 's/^ENABLED=[01]$/ENABLED=1/' $InitFile
else
        sudo echo 'ENABLED=1' | sudo tee -a $InitFile > /dev/null
fi

if [ "$ConfigWords" -eq 0 ]
then
        sudo echo "$HAproxy_config" | sudo tee -a $ConfigFile > /dev/null
else
        sudo sed -i "/^#--${DomainName}--$/,/^#--${DomainName}--$/d" $ConfigFile
        sudo echo "$HAproxy_config" | sudo tee -a $ConfigFile > /dev/null
fi

if [ "$(pgrep haproxy)" ]; then
        sudo systemctl restart haproxy.service
else
        sudo systemctl start haproxy.service
fi
echo -e "\n${green}Completed.${reset} ✅\n"
